### ISSUE TITLE
Date

### ISSUE THREAD

**Issue by GabrielDuta** [davideciacciolo/unitn#1]
Usiamo lo standard anno/mese/giorno per le date

**Comment by davideciacciolo** [comment]
hanno già lo standard giorno/mese/anno, così adesso bisogna riconvertirle tutte...

**Comment by GabrielDuta** [comment]
Non stiamo a cambiare tutto, dico solo di usare lo standard (ISO 8601) d'ora in poi, gg/mm/aa è solo una convenzione.

**Comment by davideciacciolo** [comment]
va bene dai, ISO 8601 mi ha spaventato hahaha
