### ISSUE TITLE
new feature -> new branch

### ISSUE THREAD

**Issue by davideciacciolo** [davideciacciolo/unitn#2]
sarebbe bene aprire una nuova branch per ogni nuova "feature" (ad es. tutorato di programmazione) e poi fare merging con il main una volta terminata (ad es. a chiusura del corso), in modo da non creare confusione.

**Comment by vincenzonetti** [comment]
Secondo me è meglio limitare le branch in Analisi Geometria e Programmazione_1.
comunque gg per me che ho fatto il commit su tutta la cartella di prog_1.

**Comment by davideciacciolo** [comment]
si, possiamo fare anche così

**Comment by davideciacciolo** [comment]
creo 3 branches per i tre corsi e d'ora in avanti usiamo quelle fino a chiusura del corso
